name: CLIENT-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build and Deploy Client
    runs-on: ubuntu-latest
    steps:
      - name: 프론트엔드 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 20.x 버전 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: 프론트엔드 의존성 설치
        run: npm install
        
      - name: .env.production 파일 생성
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env.production
          
      - name: 프론트엔드 빌드
        run: npm run build

      - name: EC2 서버에 프론트엔드 dist 폴더 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "dist"
          target: "/var/www/terning-farewell"
          rm: true
